version: 1.0.{build}
image: Visual Studio 2013
clone_folder: c:\projects\caffe
build_script:
- ps: >-
    cd C:\projects\caffe\windows

    cp CommonSettings.props.example CommonSettings.props
    
    (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v2.8.6/nuget.exe', 'C:\Tools\NuGet\NuGet.exe')
    nuget restore Caffe.sln

    msbuild Caffe.sln /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:"Configuration=Debug;CpuOnlyBuild=true;UseCuDNN=false"

    msbuild Caffe.sln /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:"Configuration=Release;CpuOnlyBuild=true;UseCuDNN=false;WholeProgramOptimization=false"

    cd ..
   
    ls
    ls -recurse Build
    .\Build\Release\test_all.exe --gtest_filter=-*TestTimer*
